#!/bin/bash -e
B_DIR=$(dirname "$0")
source "${B_DIR}/backblaze.conf"
source "${B_DIR}/local.conf"

host="$(hostname -s)"
path="$1"
name="$2"
runid="$3"
backup="${host}-${name}"
logfile="${B_DIR}/logs/${backup}-$(date +%Y%m%d-%H%M%S)"
statusfile="${B_DIR}/logs/${backup}.status"
successfile="${B_DIR}/logs/${backup}.success"

if [ ! -d "${path}" ]; then
	echo "bad path: ${path}"
	exit 1
fi

mkdir -p "${B_DIR}/logs"
rm -f "${successfile}"

# Initial backup
duplicity \
 --archive-dir "${B_DIR}/.state" \
 --asynchronous-upload \
 --encrypt-sign-key "${ENC_SIGN_KEY}" \
 --full-if-older-than 31D \
 --include-filelist "${B_DIR}/${name}-include" \
 --exclude-if-present .nobackup \
 --exclude-filelist "${B_DIR}/${name}-exclude" \
 --name "${backup}" \
 --verbosity info \
 "${path}" "b2://${ACCOUNT_ID}:${APP_KEY}@mattb-${backup}" \
 2>&1 >"${logfile}"
tail -n30 "${logfile}"

# Record stats
duplicity \
 collection-status \
 "b2://${ACCOUNT_ID}:${APP_KEY}@mattb-${backup}" \
 2>&1 >>"${logfile}"

# Remove old backups
duplicity remove-all-inc-of-but-n-full \
 2 \
 "b2://${ACCOUNT_ID}:${APP_KEY}@mattb-${backup}" \
 2>&1 >>"${logfile}"
duplicity remove-older-than \
 365D \
 "b2://${ACCOUNT_ID}:${APP_KEY}@mattb-${backup}" \
 2>&1 >>"${logfile}"

# Check stats again
duplicity \
 collection-status \
 "b2://${ACCOUNT_ID}:${APP_KEY}@mattb-${backup}" \
 2>&1 | tee -a "${logfile}" | tee "${statusfile}"

# Record success
echo "$runid" >"${successfile}"
