#!/bin/bash -e
source /etc/b2-backup/local.conf
CONF_DIR=${CONF_DIR:-/etc/b2-backup}
STATE_DIR=${STATE_DIR:-/var/lib/b2-backup}
LOG_DIR=${LOG_DIR:-/var/log/b2-backup}

source "${CONF_DIR}/backblaze.conf"
DEFAULT_TARGET_PREFIX="b2://${B2_ACCOUNT_ID}:${B2_APP_KEY}@mattb-"

host="$(hostname -s)"
path="$1"
name="$2"
runid="$3"
backup="${host}-${name}"
logfile="${LOG_DIR}/${backup}-$(date +%Y%m%d-%H%M%S)"
statusfile="${LOG_DIR}/${backup}.status"
successfile="${LOG_DIR}/${backup}.success"

if [ ! -d "${path}" ]; then
	echo "bad path: ${path}"
	exit 1
fi
if [ -z "${name}" ]; then
    echo "bad backup name: ${name}"
    exit 1
fi
if [ -z "${ENC_SIGN_KEY}" ]; then
    echo "encryption/signing key not specified!"
    exit 1
fi
if [ -z "${B2_ACCOUNT_ID}" ]; then
    echo "B2 account ID not specified!"
    exit 1
fi
if [ -z "${B2_APP_KEY}" ]; then
    echo "B2 app key not specified!"
    exit 1
fi
runid=${runid:-$$}

if [ -z "${TARGET_PREFIX}" ]; then
    TARGET_PREFIX="$DEFAULT_TARGET_PREFIX"
fi
target="${TARGET_PREFIX}${backup}"

rm -f "${successfile}"

DO_FULL=""
if [ ! -e "${CONF_DIR}/${name}-onlyinc" ]; then
    DO_FULL="--full-if-older-than 31D"
fi

# Initial backup
duplicity \
 --archive-dir "${STATE_DIR}" \
 --name "${backup}" \
 --asynchronous-upload \
 --encrypt-sign-key "${ENC_SIGN_KEY}" \
 $DO_FULL \
 --include-filelist "${CONF_DIR}/${name}-include" \
 --exclude-if-present .nobackup \
 --exclude-filelist "${CONF_DIR}/${name}-exclude" \
 --verbosity info \
 "${path}" "$target" 2>&1 >"${logfile}"

# Record stats
echo "==== Status (pre-cleanup) ====" >>"${logfile}"
duplicity \
 --archive-dir "${STATE_DIR}" \
 --name "${backup}" \
 collection-status \
 "$target" 2>&1 >>"${logfile}"

# Remove old backups
if [ ! -z "$DO_FULL" ]; then
    echo "-- remove-all-inc-of-but-n-full --" >>"${logfile}"
    duplicity \
     --archive-dir "${STATE_DIR}" \
     --name "${backup}" \
     remove-all-inc-of-but-n-full 2 \
     --force \
     "$target" 2>&1 >>"${logfile}"

    echo "-- remove-old-than --" >>"${logfile}"
    duplicity \
     --archive-dir "${STATE_DIR}" \
     --name "${backup}" \
     remove-older-than 365D \
     --force \
     "$target" 2>&1 >>"${logfile}"
fi

# Check stats again
echo "==== Status (post-cleanup) ====" >>"${logfile}"
duplicity \
 --archive-dir "${STATE_DIR}" \
 --name "${backup}" \
 collection-status \
 "$target" 2>&1 | tee -a "${logfile}" | tee "${statusfile}"

# Record success
echo "$runid" >"${successfile}"
exit 0
